In [1]:
import torch
from torch import tensor

In [18]:
def mat_mul(a,b):
    ar, ac = a.shape
    br, bc = b.shape
    if ac != br:
        raise Exception('invalid shape')
    res = torch.zeros(ar,bc)   
    for row in range(ar):
        for col in range(bc):
            res[row,col] = (a[row,:] * b[:,col] ).sum()
            
    return res
        

In [19]:
m1 = torch.randn(5,10)
m2 = torch.randn(10, 3)

In [20]:
mat_mul(m1,m2)

tensor([[-5.9767, -0.3922,  0.4314],
        [ 0.8785, -0.1318,  0.7626],
        [-4.9150,  3.9445, -4.4567],
        [-3.4647,  4.5484,  3.0348],
        [-7.7347,  2.4215, -4.9602]])

In [16]:
m1[1,:].shape, m2[:,1].shape

(torch.Size([10]), torch.Size([10]))

In [17]:
m1[1,:] * m2[:,1]

tensor([-1.0897, -1.0316,  1.5028, -2.0029,  2.2291, -1.0074,  1.6176,  2.5046,
         0.9384, -0.1685])

In [21]:
t1 = tensor([1,2,3]).float()

In [24]:
t1.unsqueeze(0)

tensor([[1., 2., 3.]])

In [25]:
t1[None]

tensor([[1., 2., 3.]])

In [26]:
t1.unsqueeze(-1)

tensor([[1.],
        [2.],
        [3.]])

In [27]:
t1

tensor([1., 2., 3.])

In [33]:
t1.unsqueeze(0).view(-1,1)

tensor([[1.],
        [2.],
        [3.]])

In [35]:
def mat_mul(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    assert ac == br
    res = torch.zeros(ar,bc)
    for row in range(ar):
        res[row] = (a[ar].unsqueeze(-1) * b).sum(0)
    return res

In [47]:
(m1[0].unsqueeze(-1) * m2).sum(0)

tensor([-5.9767, -0.3922,  0.4314])

In [48]:
A = torch.randn(16, 8, 5, 128, 128)
B = torch.randn(16, 8, 5, 128, 128)
A = A.unsqueeze(3)
B = B.unsqueeze(2)
A.shape, B.shape

(torch.Size([16, 8, 5, 1, 128, 128]), torch.Size([16, 8, 1, 5, 128, 128]))

In [52]:
torch.einsum('ab,bc->ac',m1,m2)

tensor([[-5.9767, -0.3922,  0.4314],
        [ 0.8785, -0.1318,  0.7626],
        [-4.9150,  3.9445, -4.4567],
        [-3.4647,  4.5484,  3.0348],
        [-7.7347,  2.4215, -4.9602]])

In [54]:
torch.randn(200,1).squeeze().shape

torch.Size([200])